---
- name: Ensure repos directory exists
  file:
    path: /opt/repos
    state: directory
    mode: '0755'

- name: Copy repositories from Ansible controller to client
  synchronize:
    src: "{{ playbook_dir }}/../{{ item.repo_name }}/"
    dest: "/opt/repos/{{ item.repo_name }}/"
    delete: yes
    recursive: yes
    rsync_path: "sudo rsync"
  loop: "{{ deploy_repositories }}"
  delegate_to: localhost
  become: false

- name: Check if .env.example exists
  stat:
    path: "/opt/repos/{{ item.0.repo_name }}/{{ item.1 }}/.env.example"
  loop: "{{ deploy_repositories | subelements('docker_stacks', skip_missing=True) }}"
  register: env_example_files

- name: Copy env example to .env when exists
  copy:
    src: "{{ item.stat.path }}"
    dest: "{{ item.stat.path | dirname }}/.env"
    remote_src: yes
    force: no
  loop: "{{ env_example_files.results }}"
  when: item.stat.exists

- name: Deploy Docker stacks
  shell: |
    docker compose up -d
  args:
    chdir: "/opt/repos/{{ item.0.repo_name }}/{{ item.1 }}"
  loop: "{{ deploy_repositories | subelements('docker_stacks', skip_missing=True) }}"
