---
- name: Ensure repos directory exists
  file:
    path: /opt/repos
    state: directory
    mode: '0755'

- name: Copy repositories from Ansible controller to client
  synchronize:
    src: "{{ playbook_dir }}/../{{ item.repo_name }}/"
    dest: "/opt/repos/{{ item.repo_name }}/"
    delete: yes
    recursive: yes
  loop: "{{ deploy_repositories }}"
  delegate_to: localhost

- name: Copy env example to .env
  copy:
    src: "/opt/repos/{{ item.0.repo_name }}/{{ item.1 }}/.env.example"
    dest: "/opt/repos/{{ item.0.repo_name }}/{{ item.1 }}/.env"
    remote_src: yes
    force: no
  loop: "{{ deploy_repositories | subelements('docker_stacks', skip_missing=True) }}"
  ignore_errors: yes

- name: Deploy Docker stacks
  shell: |
    docker compose up -d
  args:
    chdir: "/opt/repos/{{ item.0.repo_name }}/{{ item.1 }}"
  loop: "{{ deploy_repositories | subelements('docker_stacks', skip_missing=True) }}"
