---
- name: Ensure repos directory exists
  file:
    path: /opt/repos
    state: directory
    mode: '0755'

- name: Clone applications repository
  git:
    repo: "{{ repo_url }}"
    dest: "/opt/repos/{{ repo_name }}"
    version: main
    force: yes

- name: Copy env example to .env
  copy:
    src: "/opt/repos/{{ repo_name }}/{{ item }}/.env.example"
    dest: "/opt/repos/{{ repo_name }}/{{ item }}/.env"
    remote_src: yes
    force: no
  loop: "{{ docker_stacks }}"
  ignore_errors: yes

- name: Deploy Docker stacks
  shell: |
    docker compose up -d
  args:
    chdir: "/opt/repos/{{ repo_name }}/{{ item }}"
  loop: "{{ docker_stacks }}"
