# EN: Docker infrastructure servers
# ES: Servidores de infraestructura Docker
[docker]
srv-docker-main ansible_host=192.168.56.31
srv-docker-apps ansible_host=192.168.56.32

[docker:vars]
ansible_user=javi

# EN: Main infrastructure node
# ES: Nodo principal de infraestructura
[docker_main]
srv-docker-main ansible_host=192.168.56.31

[docker_main:vars]
ansible_user=javi

# EN: Applications node
# ES: Nodo de aplicaciones
[docker_apps]
srv-docker-apps ansible_host=192.168.56.32

[docker_apps:vars]
ansible_user=javi

# EN: Client servers
# ES: Servidores cliente
[clientes]
srv-cliente ansible_host=192.168.56.60

[clientes:vars]
ansible_user=javi
