[docker]
srv-docker-main ansible_host=192.168.56.31
srv-docker-apps ansible_host=192.168.56.32

[docker:vars]
ansible_user=javi


[docker_main]
srv-docker-main ansible_host=192.168.56.31

[docker_main:vars]
ansible_user=javi

[docker_apps]
srv-docker-apps ansible_host=192.168.56.32

[docker_apps:vars]
ansible_user=javi

#---------Clientes----------#

[clientes]
srv-cliente ansible_host=192.168.56.60


[clientes:vars]
ansible_user=javi
