cliente_nombre: "cliente"
cliente_subdomain: "cliente"
cliente_dominio: "cliente.lab.local"

cliente_ip: "192.168.56.60"


core_services:
  reverse_proxy: true
  dns: true
  homepage: true
  monitoring: false
  backup: false

apps:
  nginx_test: true
  portainer_agent: false
  vaultwarden: true
  uptime_kuma: true
  technitium: true
  nextcloud: true
  duplicati: false
  homepage: false

cliente_monitoring: true
cliente_backup: true

deploy_repositories:
  - repo_name: "msp-docker-apps"
    repo_url: "git@github.com:Harlock-code/msp-docker-apps.git"
    docker_stacks:
      - nginx-test
