---
- name: Create monitoring directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/data/monitoring
    - /opt/data/monitoring/prometheus
    - /opt/data/monitoring/prometheus/data
    - /opt/data/monitoring/grafana
    - /opt/data/monitoring/loki
    - /opt/data/monitoring/loki/data
    - /opt/data/monitoring/promtail

- name: Render Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/data/monitoring/prometheus/prometheus.yml
    owner: javi
    group: javi
    mode: '0644'

- name: Render Loki config
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: /opt/data/monitoring/loki/loki-config.yml
    owner: javi
    group: javi
    mode: '0644'

- name: Render Promtail config
  ansible.builtin.template:
    src: promtail-config.yml.j2
    dest: /opt/data/monitoring/promtail/promtail-config.yml
    owner: javi
    group: javi
    mode: '0644'

- name: Set Grafana permissions
  file:
    path: /opt/data/monitoring/grafana
    owner: 472
    group: 472
    recurse: yes

- name: Set Loki permissions
  file:
    path: /opt/data/monitoring/loki
    owner: 10001
    group: 10001
    recurse: yes

- name: Set Prometheus permissions
  file:
    path: /opt/data/monitoring/prometheus
    owner: nobody
    group: nogroup
    recurse: yes

- name: Render Homepage env file
  ansible.builtin.template:
    src: homepage.env.j2
    dest: /opt/repos/msp-docker-infrastructure/homepage/.env
    owner: javi
    group: javi
    mode: '0644'
  when: inventory_hostname == "srv-docker-main"

- name: Render Monitoring env file
  ansible.builtin.template:
    src: monitoring.env.j2
    dest: /opt/repos/msp-docker-infrastructure/monitoring/.env
    owner: javi
    group: javi
    mode: '0600'
  when: inventory_hostname == "srv-docker-main"
