timezone: "Europe/Madrid"

docker_base_path: "/opt/stacks"

monitoring_enabled: true

cliente_nombre: "cliente1"
cliente_dominio: "cliente1.lab.local"

cliente_servicios:
  - nginx-test
  - portainer-agent
  - vaultwarden
  - uptime-kuma
  - technitium
  - nextcloud
  - duplicati

servicios_catalogo:

  portainer-agent:
    internal_only: true

  vaultwarden:
    domain_prefix: "vault"
    forward_host: "vaultwarden"
    forward_port: 80
    cert_name: "vault-cliente-lab"

  nginx-test:
    domain_prefix: "nginx"
    forward_host: "nginx-test"
    forward_port: 80
    cert_name: "nginx-cliente-lab"

  uptime-kuma:
    domain_prefix: "uptime"
    forward_host: "uptime-kuma"
    forward_port: 3001
    cert_name: "uptime-cliente-lab"

  technitium:
    domain_prefix: "dns"
    forward_host: "technitium"
    forward_port: 5380
    cert_name: "dns-cliente-lab"

  nextcloud:
    domain_prefix: "nextcloud"
    forward_host: "nextcloud"
    forward_port: 80
    cert_name: "nextcloud-cliente-lab"

  duplicati:
    domain_prefix: "backup"
    forward_host: "duplicati"
    forward_port: 8200
    cert_name: "backup-cliente-lab"


deploy_repositories:
  - repo_name: "msp-docker-apps"
    repo_url: "git@github.com:Harlock-code/msp-docker-apps.git"

docker_networks:
  - proxy_net
  - monitoring_net
  - backend_net

npm_url: "http://192.168.56.50:81"
npm_email: "{{ vault_npm_email }}"
npm_password: "{{ vault_npm_password }}"


dns_provider: "technitium"

technitium_url: "http://192.168.56.50:5380"
technitium_username: "admin"
technitium_password: "Template.47"

