---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base admin packages
  apt:
    name:
      - curl
      - git
      - htop
      - vim
      - net-tools
      - unzip
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
