---
- import_playbook: build_service_vars.yml

- name: Deploy MSP client services
  hosts: clientes
  become: true

  roles:

    - role: docker_stack_absent
      tags: docker_stack_absent

    - role: docker_stack
      tags: docker_stack

    - role: homepage
      tags: homepage
      when: core_services.homepage | default(false)

    - role: reverse_proxy
      tags: reverse_proxy
      when: core_services.reverse_proxy | default(false)

- import_playbook: setup_dns.yml
