# EN: Configure internal MSP PKI on client hosts
# ES: Configurar PKI interna MSP en hosts cliente

---
- name: Configurar PKI interna MSP en cliente
  hosts: clientes
  become: true

  roles:
    - pki
